### PR TITLE
X7 pull request

### PR DESCRIPTION
**Pull request by kannX**
Hi,
I resynced with your master earlier this evening and ported the UI accordingly. It looks a bit cramped on the X7 but the page structure remains intact.
I gave the latest changes a quick rundown on my X7 and at least all the values are still displayed correctly.

Cheers, kannX

### CODE REVIEW

**Comment by codecae** [comment]
Hey @kannX !

Thanks for the PR.  I'll take a look at what you've done here.  I actually started porting to the X7 using the simulator, but haven't had a chance to test it on a real transmitter.  If you'd like to take a look at it, I have created a x7_test branch that has all of the changes.

**Comment by ethomas997** [comment]
@codecae:  I've tried out the branch on my X7 transmitter; looks good.  It needed the update of changing `for i=2,#(self.values) do` to `for i=2,self.minBytes do` in "vtx.lua", but other than that it works.  I've looked mostly at the VTX screen; just scrolled through the others at this point.

One thing is that sometimes if I page quickly through the screens it can crash with this error:  pwm.lua:38  "attempt to perform arith"

I'm working on porting my "vtx freq editable" mods to these scripts.  https://github.com/betaflight/betaflight-tx-lua-scripts/pull/41

**Comment by codecae** [comment]
@ethomas997 sounds good!  please review vtx_presave_fix to see an issue I recently resolved with vtx page saves.  Simplified it a bit.  Will probably make your life easier.

Feel free to create a PR whenever.  Don't worry about minifying the scripts.  TravisCI will check your code and minify it automatically.

**Comment by ethomas997** [comment]
@codecae: Will do.  What do you think about bringing the X7 branch/directory into the 'master'?  Looks like it's in good shape to me.

**Comment by codecae** [comment]
Need to build some similar logic with the crossfire scripts in order to do that.  need to design some sort of dynamic loading based on the radio

**Comment by codecae** [comment]
Implementation is far behind current head and would require significant rework for merge.  Existing x7 version is fairly current and works well.  Duplicate effort, I'm afraid.  Thank you for your submission, though!

**Pull request closed without merging**
