### PR TITLE
Update rates1.lua

### PR DESCRIPTION
**Pull request by putimir**
Minor layout update to better fit Horus screens

### CODE REVIEW

**Comment by putimir** [comment]
img_20171106_164149

**Comment by codecae** [comment]
might be a little tight.. can we put a little more space between RC Rate and Super Rate?

**Comment by putimir** [comment]
Hi, they are actually equally spaced, I was testing the case, where all fields have 2 decimal places...

img_20171106_200118


Maybe smaller font?

**Comment by codecae** [comment]
try removing ```to = MIDSIZE``` and let it use the default font size.  it just looks a little crowded

**Pull request closed without merging**
